# 01 서블릿 예외 처리 

서블릿은 2가지 방식으로 예외처리를 지원
<br>① Exception (예외)<br>
② response.sendError (HTTP 상태 코드, 오류 메시지)

## Exception (예외)
### 자바 직접 실행 하는 경우 (기본적인 매커니즘)
자바의 메인 메서드를 실행하는 경우 `main` 이라는 쓰레드가 실행된다. 

예외가 발생하면 상위로 계속해서 던져지게 되는데 이게 `main` 메서드를 넘어서 예외가 던져지면, 예외 정보를 남기고 해당 쓰레드는 종료된다. 

### 웹 어플리케이션 
웹 어플리케이션은 사용자 요청별로 별도의 쓰레드가 할당되고, 서블릿 컨테이너 안에서 실행된다. 

어플리케이션에서 예외가 발생했을 때 try-catch 로 예외를 잡아서 처리하면 아무런 문제가 없다. 

그런데, 어플리케이션에서 예외를 잡지 못하고, 서블릿 밖으로 예외가 전달되면 어떻게 될까 ?

```
WAS <- 필터 <- 서블릿 <- 인터셉터 <- 컨트롤러 (예외 발생)
```

WAS 까지 예외가 올라왔을 때 테스트 

**첫번째, 스프링 부트가 제공하는 기본 예외 페이지 끄기 <br>**
application.properties
```
server.error.whitelabel.enabled=false
```

**두번째, 테스트 컨트롤러 만들어주기**
```java
@Slf4j
@Controller
public class ServletExceptionController {

    @GetMapping("/error-ex")
    public void errorEx() {
        throw new RuntimeException("예외 발생!");
    }

}
```
➡️ 호출 시 HTTP 상태 코드 500 으로 에러 발생<br>
⭐️Exception 의 경우 서버 내부에서 처리할 수 없는 오류라고 판단해서 HTTP 상태 코드 500을 반환함. 

아무것도 없는 페이지를 호출 할 때에는 404 오류 발생 

## response.sendError(HTTP 상태코드, 오류 메시지)
오류가 발생했을 때 HttpServletResponse 가 제공하는 sendError 메소드를 사용해도 된다. 
바로 예외가 발생하는 것은 아니지만, 서블릿 컨테이너에게 오류가 발생했다는 것을 전달할 수 있다.

response.sendError(HTTP 상태코드)<br>
response.sendError(HTTP 상태코드, 오류 메시지)

ServletExceptionController 에 코드 추가 
```java
@GetMapping("/error-404")
public void error404(HttpServletResponse response) throws IOException {
response.sendError(404, "404 오류 발생");
}

@GetMapping("/error-500")
public void error500(HttpServletResponse response) throws IOException {
response.sendError(500);
}
```

**sendError 흐름**<br>
컨트롤러에서 sendError 를 호출하는 경우 response 내부에 오류가 발생했다는 상태를 저장해둔다. <br>
그리고 서블릿 컨테이너가 고객 응답 전에 response 에서 sendError 가 호출되었는지 확인하고, 호출된 경우 설정한 오류 코드에 맞춰서 기본 오류 페이지를 노출한다. 